[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
lucky_sol = "5X6xVcL5Fc9qzWXrRSJfnqLu6xXpLmHZX1szaGoj5NHr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
add_metadata = "yarn run ts-node scripts/add_metadata.ts"
buy_ticket = "yarn run ts-node scripts/buy_ticket.ts"
create_lottery = "yarn run ts-node scripts/create_lottery.ts"
create_mint = "yarn run ts-node scripts/create_mint.ts"
get_lotteries = "yarn run ts-node scripts/get_lotteries.ts"
get_lotteries_short = "yarn run ts-node scripts/get_lotteries_short.ts"
get_tickets = "yarn run ts-node scripts/get_tickets.ts"
initialize = "yarn run ts-node scripts/initialize.ts"
set_winner = "yarn run ts-node scripts/set_winner.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
transfer_mint = "yarn run ts-node scripts/transfer_mint.ts"

[test]
startup_wait = 15000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
